# fly.toml app configuration file generated for judgeapi on 2024-12-15T11:53:20+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'judgeapi'
primary_region = 'nrt'

[build]

[env]
  FLASK_APP = 'app.py'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
